kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
    alpha.image.policy.openshift.io/resolve-names: '*'
    deployment.kubernetes.io/revision: '2'
    image.openshift.io/triggers: >-
      [{"from":{"kind":"ImageStreamTag","name":"api-envio-email:1.0.1","namespace":"e83carvalho"},"fieldPath":"spec.template.spec.containers[?(@.name==\"api-envio-email\")].image","pause":"false"}]
    openshift.io/generated-by: OpenShiftWebConsole
  selfLink: /apis/apps/v1/namespaces/e83carvalho/deployments/api-envio-email
  resourceVersion: '241901792'
  name: api-envio-email
  uid: 159eeb38-f2df-49bf-b75e-38c952fb5959
  creationTimestamp: '2023-01-29T17:20:07Z'
  generation: 3
  managedFields:
    - manager: kube-controller-manager
      operation: Update
      apiVersion: apps/v1
      time: '2023-01-29T17:20:55Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            'f:deployment.kubernetes.io/revision': {}
        'f:status':
          'f:availableReplicas': {}
          'f:conditions':
            .: {}
            'k:{"type":"Available"}':
              .: {}
              'f:lastTransitionTime': {}
              'f:lastUpdateTime': {}
              'f:message': {}
              'f:reason': {}
              'f:status': {}
              'f:type': {}
            'k:{"type":"Progressing"}':
              .: {}
              'f:lastTransitionTime': {}
              'f:lastUpdateTime': {}
              'f:message': {}
              'f:reason': {}
              'f:status': {}
              'f:type': {}
          'f:observedGeneration': {}
          'f:readyReplicas': {}
          'f:replicas': {}
          'f:updatedReplicas': {}
    - manager: Mozilla
      operation: Update
      apiVersion: apps/v1
      time: '2023-01-29T17:22:24Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:alpha.image.policy.openshift.io/resolve-names': {}
            'f:image.openshift.io/triggers': {}
            'f:openshift.io/generated-by': {}
          'f:labels':
            .: {}
            'f:app': {}
            'f:app.kubernetes.io/component': {}
            'f:app.kubernetes.io/instance': {}
            'f:app.kubernetes.io/part-of': {}
            'f:app.openshift.io/runtime': {}
            'f:app.openshift.io/runtime-namespace': {}
        'f:spec':
          'f:progressDeadlineSeconds': {}
          'f:replicas': {}
          'f:revisionHistoryLimit': {}
          'f:selector':
            'f:matchLabels':
              .: {}
              'f:app': {}
          'f:strategy':
            'f:rollingUpdate':
              .: {}
              'f:maxSurge': {}
              'f:maxUnavailable': {}
            'f:type': {}
          'f:template':
            'f:metadata':
              'f:annotations':
                .: {}
                'f:openshift.io/generated-by': {}
              'f:labels':
                .: {}
                'f:app': {}
                'f:deploymentconfig': {}
            'f:spec':
              'f:containers':
                'k:{"name":"api-envio-email"}':
                  'f:envFrom': {}
                  'f:image': {}
                  'f:terminationMessagePolicy': {}
                  .: {}
                  'f:resources': {}
                  'f:terminationMessagePath': {}
                  'f:imagePullPolicy': {}
                  'f:ports':
                    .: {}
                    'k:{"containerPort":8888,"protocol":"TCP"}':
                      .: {}
                      'f:containerPort': {}
                      'f:protocol': {}
                  'f:name': {}
              'f:dnsPolicy': {}
              'f:restartPolicy': {}
              'f:schedulerName': {}
              'f:securityContext': {}
              'f:terminationGracePeriodSeconds': {}
  namespace: e83carvalho
  labels:
    app: api-envio-email
    app.kubernetes.io/component: api-envio-email
    app.kubernetes.io/instance: api-envio-email
    app.kubernetes.io/part-of: fiap
    app.openshift.io/runtime: spring-boot
    app.openshift.io/runtime-namespace: e83carvalho
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-envio-email
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: api-envio-email
        deploymentconfig: api-envio-email
      annotations:
        openshift.io/generated-by: OpenShiftWebConsole
    spec:
      containers:
        - name: api-envio-email
          image: >-
            image-registry.openshift-image-registry.svc:5000/e83carvalho/api-envio-email@sha256:0577eb0cb144cd2540b636c639a602ca2a225d84911327e4e413258daa2e94d0
          ports:
            - containerPort: 8888
              protocol: TCP
          envFrom:
            - configMapRef:
                name: configmap-api-envio-email
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
status:
  observedGeneration: 3
  replicas: 2
  updatedReplicas: 2
  readyReplicas: 2
  availableReplicas: 2
  conditions:
    - type: Progressing
      status: 'True'
      lastUpdateTime: '2023-01-29T17:20:30Z'
      lastTransitionTime: '2023-01-29T17:20:07Z'
      reason: NewReplicaSetAvailable
      message: ReplicaSet "api-envio-email-6cf6cc974c" has successfully progressed.
    - type: Available
      status: 'True'
      lastUpdateTime: '2023-01-29T17:20:55Z'
      lastTransitionTime: '2023-01-29T17:20:55Z'
      reason: MinimumReplicasAvailable
      message: Deployment has minimum availability.
